const Prim_void = () => { throw new Error('void') };
const Prim_unit = {_tag: 'Unit', val: null};
const Prim_true = true;
const Prim_false = false;
const Prim_if = c => a => b => c ? a(Prim_unit) : b(Prim_unit);
const Prim_pair = a => b => ({ _tag: 'Pair', val: [a, b] });
const Prim_fst = p => p.val[0];
const Prim_fst = p => p.val[1];
const Prim_inl = a => ({ _tag: 'L', val: a });
const Prim_inr = b => ({ _tag: 'R', val: b });
const Prim_case = a => b => s => s._tag === 'L' ? a(s.val) : b(s.val);
const Prim_appendStr = a => b => a + b;
